import 'package:flutter/material.dart';


// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Testscreen extends StatelessWidget {
  const Testscreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          MyCart(),
        ]),
      ),
    );
  }
}

class MyCart extends StatelessWidget {
  const MyCart({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: MediaQuery.of(context).size.height * 0.8,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            gradient: const LinearGradient(
            begin: Alignment(0.00, -1.00),
            end: Alignment(0, 1),
            colors: [Color(0xFFE7EBEF), Color(0xFFF7ECCF), Color(0xFFF6EBCF)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 51,
                top: 235,
                child: SizedBox(
                  width: 327,
                  height: 110,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 327,
                          height: 110,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 207,
                                top: 0,
                                child: SizedBox(
                                  width: 120,
                                  height: 110,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 120,
                                          height: 110,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD7D7D7),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 120,
                                          height: 110,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD7D7D7),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 4,
                                child: Container(
                                  width: 164,
                                  height: 102,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: const BoxDecoration(),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Container(
                                        width: 16,
                                        height: 16,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF2C3E50),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                        ),
                                      ),
                                      const Text(
                                        'Hard Cover',
                                        style: TextStyle(
                                          color: Color(0xFFBBBBBB),
                                          fontSize: 13,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                      const Text(
                                        '\$16',
                                        style: TextStyle(
                                          color: Color(0xFF424347),
                                          fontSize: 14,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w500,
                                          height: 0,
                                          letterSpacing: -0.16,
                                        ),
                                      ),
                                      const Text(
                                        '・',
                                        style: TextStyle(
                                          color: Color(0xFFD7D7D7),
                                          fontSize: 14,
                                          fontFamily: 'PingFangSC',
                                          fontWeight: FontWeight.w600,
                                          height: 0,
                                        ),
                                      ),
                                      const Text(
                                        'In stock',
                                        style: TextStyle(
                                          color: Color(0xFF2C3E50),
                                          fontSize: 14,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                          letterSpacing: -0.16,
                                        ),
                                      ),
                                      Container(
                                        width: 96,
                                        height: 32,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: const BoxDecoration(),
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 96,
                                                height: 32,
                                                decoration: const BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/96x32"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 76,
                                              top: 12,
                                              child: Container(
                                                width: 8,
                                                height: 8,
                                                decoration: const BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage("https://via.placeholder.com/8x8"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ),
                                            const Positioned(
                                              left: 46,
                                              top: 6,
                                              child: Text(
                                                '1',
                                                style: TextStyle(
                                                  color: Color(0xFFBBBBBB),
                                                  fontSize: 14,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 32,
                                        height: 32,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFF5F5F5),
                                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                        ),
                                      ),
                                      Container(
                                        width: 12,
                                        height: 14,
                                        decoration: const BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/12x14"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 22,
                        top: 2,
                        child: Text(
                          'Jungle Book',
                          style: TextStyle(
                            color: Color(0xFF424347),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 0,
                            letterSpacing: -0.18,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 51,
                top: 527,
                child: SizedBox(
                  width: 327,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 207,
                        top: 0,
                        child: SizedBox(
                          width: 120,
                          height: 110,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 120,
                                  height: 110,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFD7D7D7),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 120,
                                  height: 110,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFD7D7D7),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 4,
                        child: Container(
                          width: 164,
                          height: 102,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              const Text(
                                'Jungle Book',
                                style: TextStyle(
                                  color: Color(0xFF424347),
                                  fontSize: 16,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w500,
                                  height: 0,
                                  letterSpacing: -0.18,
                                ),
                              ),
                              const Text(
                                'Jungle Book',
                                style: TextStyle(
                                  color: Color(0xFF424347),
                                  fontSize: 16,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w500,
                                  height: 0,
                                  letterSpacing: -0.18,
                                ),
                              ),
                              Container(
                                width: 16,
                                height: 16,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: const BorderSide(width: 2, color: Color(0xFFDEDEDE)),
                                    borderRadius: BorderRadius.circular(2),
                                  ),
                                ),
                              ),
                              const Text(
                                'Hard Cover',
                                style: TextStyle(
                                  color: Color(0xFFBBBBBB),
                                  fontSize: 13,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                              const Text(
                                '・',
                                style: TextStyle(
                                  color: Color(0xFFD7D7D7),
                                  fontSize: 14,
                                  fontFamily: 'PingFangSC',
                                  fontWeight: FontWeight.w600,
                                  height: 0,
                                ),
                              ),
                              const Text(
                                '\$36',
                                style: TextStyle(
                                  color: Color(0xFF424347),
                                  fontSize: 14,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w500,
                                  height: 0,
                                  letterSpacing: -0.16,
                                ),
                              ),
                              const Text(
                                'Out of stock',
                                style: TextStyle(
                                  color: Color(0xFFBBBBBB),
                                  fontSize: 14,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w500,
                                  height: 0,
                                  letterSpacing: -0.16,
                                ),
                              ),
                              Container(
                                width: 96,
                                height: 32,
                                clipBehavior: Clip.antiAlias,
                                decoration: const BoxDecoration(),
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(
                                        width: 96,
                                        height: 32,
                                        decoration: const BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/96x32"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 76,
                                      top: 12,
                                      child: Container(
                                        width: 8,
                                        height: 8,
                                        decoration: const BoxDecoration(
                                          image: DecorationImage(
                                            image: NetworkImage("https://via.placeholder.com/8x8"),
                                            fit: BoxFit.fill,
                                          ),
                                        ),
                                      ),
                                    ),
                                    const Positioned(
                                      left: 46,
                                      top: 6,
                                      child: Text(
                                        '1',
                                        style: TextStyle(
                                          color: Color(0xFFBBBBBB),
                                          fontSize: 14,
                                          fontFamily: 'Poppins',
                                          fontWeight: FontWeight.w400,
                                          height: 0,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              Container(
                                width: 32,
                                height: 32,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFF5F5F5),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                ),
                              ),
                              Container(
                                width: 12,
                                height: 14,
                                decoration: const BoxDecoration(
                                  image: DecorationImage(
                                    image: NetworkImage("https://via.placeholder.com/12x14"),
                                    fit: BoxFit.fill,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 8,
                top: 730,
                child: SizedBox(width: 375, height: 178),
              ),
              Positioned(
                left: 45,
                top: 780,
                child: Container(
                  width: 338,
                  height: 60,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 338,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF2C3E50),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(40),
                            ),
                            shadows: const [
                              BoxShadow(
                                color: Color(0x19000000),
                                blurRadius: 20,
                                offset: Offset(0, 8),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 122,
                        top: 22,
                        child: Text(
                          'Check Out',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 18,
                            fontFamily: 'Brown',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 7,
                child: Container(
                  width: 375,
                  height: 192,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 192,
                        child: Container(
                          width: 375,
                          height: 192,
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0),
                            boxShadow: const [
                              BoxShadow(
                                color: Color(0x19000000),
                                blurRadius: 20,
                                offset: Offset(0, 2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 24,
                        top: 99,
                        child: Text(
                          'Cart',
                          style: TextStyle(
                            color: Color(0xFF424347),
                            fontSize: 40,
                            fontFamily: 'Brown',
                            fontWeight: FontWeight.w700,
                            height: 0,
                            letterSpacing: -1,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 36,
                        top: 169,
                        child: Container(
                          width: 332,
                          height: 13,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                          child: Stack(
                            children: [
                              const Positioned(
                                left: 142,
                                top: 0,
                                child: Text(
                                  'Select All',
                                  style: TextStyle(
                                    color: Color(0xFF3E3E3E),
                                    fontSize: 11,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 235,
                                top: 0,
                                child: Text(
                                  'Delete Selected',
                                  style: TextStyle(
                                    color: Color(0xFF3E3E3E),
                                    fontSize: 11,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '3 items',
                                  style: TextStyle(
                                    color: Color(0xFFBBBBBB),
                                    fontSize: 11,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 220,
                                top: 0,
                                child: Container(
                                  width: 11,
                                  height: 12,
                                  decoration: const BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/11x12"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 13,
                        top: 19,
                        child: Container(
                          width: 23,
                          height: 14,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/23x14"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 51,
                top: 381,
                child: SizedBox(
                  width: 327,
                  height: 110,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 207,
                        top: 0,
                        child: SizedBox(
                          width: 120,
                          height: 110,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 120,
                                  height: 110,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFD7D7D7),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 120,
                                  height: 110,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFD7D7D7),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 4,
                        child: Container(
                          width: 164,
                          height: 102,
                          clipBehavior: Clip.antiAlias,
                          decoration: const BoxDecoration(),
                          child: Stack(
                            children: [
                              const Positioned(
                                left: 28,
                                top: 44,
                                child: Text(
                                  '\$16',
                                  style: TextStyle(
                                    color: Color(0xFF424347),
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w500,
                                    height: 0,
                                    letterSpacing: -0.16,
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 52,
                                top: 41,
                                child: Text(
                                  '・',
                                  style: TextStyle(
                                    color: Color(0xFFD7D7D7),
                                    fontSize: 14,
                                    fontFamily: 'PingFangSC',
                                    fontWeight: FontWeight.w600,
                                    height: 0,
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 66,
                                top: 41,
                                child: Text(
                                  'In stock',
                                  style: TextStyle(
                                    color: Color(0xFF2C3E50),
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                    letterSpacing: -0.16,
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 28,
                                top: 22,
                                child: Text(
                                  'Hard Cover',
                                  style: TextStyle(
                                    color: Color(0xFFBBBBBB),
                                    fontSize: 13,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28,
                                top: 70,
                                child: Container(
                                  width: 96,
                                  height: 32,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: const BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 96,
                                          height: 32,
                                          decoration: const BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/96x32"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 76,
                                        top: 12,
                                        child: Container(
                                          width: 8,
                                          height: 8,
                                          decoration: const BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/8x8"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                      const Positioned(
                                        left: 46,
                                        top: 6,
                                        child: Text(
                                          '1',
                                          style: TextStyle(
                                            color: Color(0xFFBBBBBB),
                                            fontSize: 14,
                                            fontFamily: 'Poppins',
                                            fontWeight: FontWeight.w400,
                                            height: 0,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 132,
                                top: 70,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF5F5F5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 142,
                                top: 79,
                                child: Container(
                                  width: 12,
                                  height: 14,
                                  decoration: const BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/12x14"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 16,
                                  height: 16,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF2C3E50),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 23,
                        top: 2,
                        child: Text(
                          'Jungle Book',
                          style: TextStyle(
                            color: Color(0xFF424347),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 0,
                            letterSpacing: -0.18,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}